#ifndef TH_PHASE_MOTOR_CONNECTION_H
#define TH_PHASE_MOTOR_CONNECTION_H

#include "stm32f4xx_hal.h"

#define TH_PHASE_MOTOR_PORT GPIOD
#define TH_PHASE_MOTOR_PIN GPIO_PIN_2

#endif // TH_PHASE_MOTOR_CONNECTION_H