#include "command/partial/err.h"

err ERR = {0};

void err_init()
{
    // STRUCTURE ERRORS

    ERR.UNDEFINED = 1;

    ERR.COMMAND_TOO_SHORT = 2;
    ERR.COMMAND_TOO_LONG = 3;
    ERR.COMMAND_INCORRECT_BEGINING = 4;
    ERR.COMMAND_INCORRECT_END = 5;

    ERR.NO_PARAMS = 6;
    ERR.ONE_PARAM_ONLY = 7;
    ERR.TO_MANY_PARAMS = 8;

    ERR.NO_INDEX_KEY = 9;
    ERR.INCORRECT_INDEX_VALUE = 10;

    ERR.NO_OPERATION_KEY = 11;
    ERR.INCORRECT_OPERATION_VALUE = 12;

    ERR.NO_STEPPER_KEY = 13;
    ERR.INCORRECT_STEPPER_VALUE = 14;

    ERR.NO_ENDSTOP_KEY = 15;
    ERR.INCORRECT_ENDSTOP_VALUE = 16;

    ERR.NO_SPEED_KEY = 17;
    ERR.INCORRECT_SPEED_VALUE = 18;

    ERR.NO_ACCELERATION_KEY = 19;
    ERR.INCORRECT_ACCELERATION_VALUE = 20;

    ERR.NO_STATE_KEY = 21;
    ERR.INCORRECT_STATE_VALUE = 22;

    ERR.NO_WAY_KEY = 23;
    ERR.INCORRECT_WAY_VALUE = 24;

    ERR.NO_DIRECTION_KEY = 25;
    ERR.INCORRECT_DIRECTION_VALUE = 26;

    ERR.NO_COOLANT_KEY = 27;
    ERR.INCORRECT_COOLANT_VALUE = 28;

    // ENVIRONMENT STATE ERRORS

    ERR.LIMIT_SWITCH_REACHED = 29;

    ERR.STEPPER_SPEED_NOT_SET = 30;
    ERR.STEPPER_NOT_RUNNING = 31;
    ERR.STEPPER_NOT_PAUSED = 32;
    ERR.STEPPER_NOT_RUNNING_OR_PAUSED = 33;

    ERR.STEPPER_ALREADY_RUNNING = 34;
    ERR.STEPPER_ALREADY_PAUSED = 35;

    ERR.PROCESS_NOT_CONFIGURED = 36;
    ERR.PROCESS_NOT_HALTED = 37;
    ERR.PROCESS_NOT_RUNNING = 38;
    ERR.PROCESS_ALREADY_RUNNING = 39;

    ERR.OPERATION_NOT_ALLOWED = 40;
}
