#include "command/partial/err.h"

err ERR;

void err_init()
{
    ERR.NO_ERROR = 0;
    ERR.ERROR = 1;

    ERR.INVALID_COMMAND_LENGTH = 2;
    ERR.NO_PARAMS = 3;
    ERR.ONE_PARAM_ONLY = 4;
    ERR.TO_MANY_PARAMS = 5;

    ERR.NO_INDEX_KEY = 6;
    ERR.INVALID_INDEX_VALUE = 7;

    ERR.NO_OPERATION_KEY = 8;
    ERR.INVALID_OPERATION_VALUE = 9;

    ERR.NO_STEPPER_KEY = 10;
    ERR.INVALID_STEPPER_VALUE = 11;

    ERR.NO_SPEED_KEY = 12;
    ERR.INVALID_SPEED_VALUE = 13;

    ERR.NO_STATE_KEY = 14;
    ERR.INVALID_STATE_VALUE = 15;

    ERR.NO_WAY_KEY = 16;
    ERR.INVALID_WAY_VALUE = 17;

    ERR.NO_DIRECTION_KEY = 18;
    ERR.INVALID_DIRECTION_VALUE = 19;

    ERR.OPERATION_NOT_ALLOWED = 20;
}