#ifndef REQUEST_MANAGER_H
#define REQUEST_MANAGER_H

#include <stdint.h>

// 8 STEPS TO PROCESS REQUEST
/*
    STEP 1: EXPLODE FOR PAIRS KEY:VALUE
    STEP 2: GENERAL VALIDATION (RECORDS, INDEX, OPERATION CHECKS)
    STEP 3: GET INDEX AND OPERATION TYPE
    STEP 4: SCHRINK DATA TO LEAVE ONLY NEEDED DATA (REMOVE GATHERED INDEX AND OPERATION RECORDS)
    STEP 5: CHECK IF OPERATION TYPE IS KNOWN AND PREPARE DATA FOR NEXT STEPS (DEPEND ON OPERATION)
    STEP 6: VALIDATE REQUEST KEYS
    STEP 7: VALIDATE REQUEST VALUES AND ENVIRONMENT STATES
    STEP 8: EXECUTE REQUEST
*/

uint8_t *request_process(uint8_t *request);

#endif // REQUEST_MANAGER_H