#include "clock_manager.h"

#include "stm32f4xx_hal.h"

void clocks_init()
{
    //SystemCoreClock = 160000000; // 160 MHz

    __HAL_RCC_GPIOA_CLK_ENABLE();  
    __HAL_RCC_GPIOB_CLK_ENABLE();   
    __HAL_RCC_GPIOC_CLK_ENABLE();

    __HAL_RCC_USART2_CLK_ENABLE();
    __HAL_RCC_DMA1_CLK_ENABLE();

    __HAL_RCC_TIM2_CLK_ENABLE();
    __HAL_RCC_TIM3_CLK_ENABLE();
    __HAL_RCC_TIM4_CLK_ENABLE();
    __HAL_RCC_TIM5_CLK_ENABLE();
    __HAL_RCC_TIM9_CLK_ENABLE();
    __HAL_RCC_TIM10_CLK_ENABLE();
    __HAL_RCC_TIM12_CLK_ENABLE();
    __HAL_RCC_TIM13_CLK_ENABLE();
}

void clocks_deinit()
{
    __HAL_RCC_GPIOA_CLK_DISABLE(); 
    __HAL_RCC_GPIOB_CLK_DISABLE(); 
    __HAL_RCC_GPIOC_CLK_DISABLE();

    __HAL_RCC_USART2_CLK_DISABLE();
    __HAL_RCC_DMA1_CLK_DISABLE();

    __HAL_RCC_TIM2_CLK_DISABLE();
    __HAL_RCC_TIM3_CLK_DISABLE();
    __HAL_RCC_TIM4_CLK_DISABLE();
    __HAL_RCC_TIM5_CLK_DISABLE();
    __HAL_RCC_TIM9_CLK_DISABLE();
    __HAL_RCC_TIM10_CLK_DISABLE();
    __HAL_RCC_TIM12_CLK_DISABLE();
    __HAL_RCC_TIM13_CLK_DISABLE();
}
